name: Issue Doctor

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and run the tests
      run: |
        cargo build --release
        cargo test --release
    - name: Run codeblock from the issue
      run: |
        labels=''
        echo '${{ github.event.issue.body }}' > issue_body
        sed -n '/```test_start/,/```/p' issue_body | sed '/^```/ d' > src/reproduce_issue.rs
        if cargo check --tests; then
          if cargo test --release reproduce_issue; then
            echo 'The issue is not reproducible'
            labels+=\"not-reproducible\"
          else
            labels+=\"reproducible\"
          fi
        else
          echo 'There are compilation errors'
          labels+='"not-reproducible", "errored"'
        fi
        curl -u lionel1704:${{ secrets.GH_TOKEN }} -X PUT https://api.github.com/repos/lionel1704/gh-actions-demo/issues/${{ github.event.issue.number }}/labels -d "{ \"labels\" : [$labels]}"
