name: Issue Doctor

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the project
      run: cargo build --release
    - name: Print something
      run: ./target/release/hello_world ${{ toJson(github) }}
    
