name: Issue Doctor

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and run the tests
      run: |
        cargo build --release
        cargo test --release
    - name: Run codeblock from the issue
      run: |
        echo '${{ github.event.issue.body }}' > issue_body
        sed -n '/```test_start/,/```/p' issue_body | sed '/^```/ d' > reproduce_issue.rs
        cargo test --release reproduce_issue
    - name: Print payload
      run: echo "${{ toJson(github) }}"
